// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8NdFCRsHOmq48w1KWh54Os-Fzn8TwtN8',
    appId: '1:948155745931:web:6b9a7a6fbebb423c7e368e',
    messagingSenderId: '948155745931',
    projectId: 'happier-7cc4a',
    authDomain: 'happier-7cc4a.firebaseapp.com',
    storageBucket: 'happier-7cc4a.firebasestorage.app',
    measurementId: 'G-MY5ZRMYKXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlnvVdrGuua56T8lFevEodMz9wGGUCiGc',
    appId: '1:948155745931:android:c6f45222f19d936a7e368e',
    messagingSenderId: '948155745931',
    projectId: 'happier-7cc4a',
    storageBucket: 'happier-7cc4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCadOAPdSfwWAOCmqm7ss2vV8275P8DRA8',
    appId: '1:948155745931:ios:d135df7f72714e567e368e',
    messagingSenderId: '948155745931',
    projectId: 'happier-7cc4a',
    storageBucket: 'happier-7cc4a.firebasestorage.app',
    androidClientId: '948155745931-ri3cft8pjhptrt00i3co6hrpheojltjg.apps.googleusercontent.com',
    iosClientId: '948155745931-cl0c8c8vbn0nhlqrqct96cuotbgbkej3.apps.googleusercontent.com',
    iosBundleId: 'com.example.happierMeditation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCadOAPdSfwWAOCmqm7ss2vV8275P8DRA8',
    appId: '1:948155745931:ios:d135df7f72714e567e368e',
    messagingSenderId: '948155745931',
    projectId: 'happier-7cc4a',
    storageBucket: 'happier-7cc4a.firebasestorage.app',
    androidClientId: '948155745931-ri3cft8pjhptrt00i3co6hrpheojltjg.apps.googleusercontent.com',
    iosClientId: '948155745931-cl0c8c8vbn0nhlqrqct96cuotbgbkej3.apps.googleusercontent.com',
    iosBundleId: 'com.example.happierMeditation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8NdFCRsHOmq48w1KWh54Os-Fzn8TwtN8',
    appId: '1:948155745931:web:2cfd784d803ccbcb7e368e',
    messagingSenderId: '948155745931',
    projectId: 'happier-7cc4a',
    authDomain: 'happier-7cc4a.firebaseapp.com',
    storageBucket: 'happier-7cc4a.firebasestorage.app',
    measurementId: 'G-PKCSBCQDCQ',
  );
}
